development:
  adapter: jdbcmysql
  encoding: utf8
  reconnect: false
  database: geocoder_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: jdbcmysql
  encoding: utf8
  reconnect: false
  database: geocoder_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

