development:
  adapter: postgresql
  encoding: unicode
  database: geocoder_development
  pool: 5
  username: alex
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: geocoder_test
  pool: 5
  username: alex
  password: 
